### ISSUE TITLE
Global Storage of values

### ISSUE THREAD

**Issue by Zardoz89** [adam4813/Sigma#111]
As Sigma is growing, is being necessary to store and retrieve some global values of configuration across all components and systems.
Values like if is enable anisotropic filtering, music volumen, etc...

A hash table could do the work but we need a way of storing a generic value on t it, as these values could be a integer, a float, a string, etc....
Actually I played with two ideas : 
- Implementing a basic Variant type and using it with unordered_map of STL
- Adapting Property class to be used with unordered_set or unordered_map of STL

The Variant way, stores the value in a union and stores the type in a enumeration so could retrieve the value type with a simple method. Using a enumeration is more reliable that typeid.name() were is dependent of compiler and compiler settings.

The Property way, reuses previous code and is a bit more easy to use, as is not necessary to indicate the type to the Ctor of the value. ~~But I find problems storing strings and unordered_set.find method not ends to work (very important!)~~
### Variant way :

**Pro** : 
- Type is know all time in a reliable way.
- Can store strings, and can be extended to store other custom types.
- Avoids pointers and inheritance.

**Contra** : 
- A bit ugly way to store a key-value entry (but can be fixed with overload Ctors) :
  
   globalstore["eggs"] = Value (TypeVal::T_INT);
   globalstore["eggs"].SetInt(32);
- More bloated code that Property
- Re invent the wheel as Property class does something similar functionality.
### Property way :

**Pro** : 
- Uses templates and can guess the type of the value. Inserting a value is like : 
  
  globalstore.insert(Property("Pr PI", 3.1416f));
- Existent code base
- Only need add extra functionality to allow to be stored and iterate in a unordered_map or unordered_set

**Contra** : 
- ~~Actually have problems storing std:strings (Or I doing something very wrong)~~
- ~~Find method is not working as should be, what makes it nearly useless. But could be fixed.~~
- Find  if a entry exists is a bit cumbersome : 
  
    auto it = gs.find(Property("Pr PI", 0));
    if (it != gs.end()) { ...
- Touching it could break existent code base.
- Type can't be know in a reliable way at runtime (I believe). For reading know properties were you expect a type for a entry is not a problem (Volume is a integer, etc...). It could be problematic if you need to list the whole list of values with a loop, so you not know what type is every entry.

You could check both versions in this gist : https://gist.github.com/Zardoz89/8165988
 It compiles alone, only needing -std=c++11

**Comment by adam4813** [comment]
It's crashing because you are storing a const char not a std::string.  :)

**Comment by Zardoz89** [comment]
I think that I was very sleepy. Using a std::string works perfect.

**Comment by s-ol** [comment]
well, you could create static methods for the first Version:
`globalstore["eggs"] = Value.fromInt( 36 );`

Or have overloaded constructors (bad for storing other stuff):

```
globalstore["eggs"] = Value( 36 );
globalstore["eggs"] = Value( TypeVal::T_INT, 36 );
```
