### ISSUE TITLE
Make graphics pipeline more flexible

### ISSUE THREAD

**Issue by wrongu** [adam4813/Sigma#117]
OpenGLSystem is currently closely-coupled with the specific shader implementations. Ideally the pipeline's code architecture would reflect the sequential and modular nature of the shading pipeline; each 'module' is a rendering pass.

Proposal (@tanderegg help me out here):
- Rendering is done by calling a sequence of render passes
- Render passes are objects inheriting from `IRenderPass`
- Each `Pass` object keeps track of its read/write targets, shader(s), and component batch(es)
- The `Pass` needs to know about shaders' implementation details, not the `OpenGLSystem`

Further thoughts:
- It is more expensive to switch between FBOs than between texture attachments within a single FBO. Ideally `Pass`es should be ordered in such a way that it takes advantage of this.
- Implementing a new post-processing effect is as easy as writing a new extension of `IRenderPass` and adding that object to the pipeline. Likewise, this makes it easy to turn effects on or off since they are encapsulated well.
- Another thing to keep in mind is that shaders can be compiled using multiple strings as a source. In theory, you could use this to have shaders "import" inputs, outputs, and functions. While I think this is a neat concept, I haven't figured out yet how it fits into the above design.

**Comment by tanderegg** [comment]
Looks good to me, this will require some experimentation to ensure that the system is maximally flexible, i.e. the engine itself should be agnostic as to what type of rendering is used (deferred, forward, light pre pass, etc), but the application should be able to define any of them through this API, and any post processing effects as well.  If you want to take a crack at this @wrongu, I'll probably start working on shadows next, and then I can work with you on this.

**Comment by Zardoz89** [comment]
Sound logic to me.

**Comment by wrongu** [comment]
Here's another thought:

The most frustrating part about dealing with framebuffers and textures seems to be that their "names" are unsigned ints. This makes it hard to keep track of them, especially when flipping between buffers... But the way that buffers read and write from/to each other is a simple dependency graph, so we could give each buffer a _name_, then have the rendering system do the buffer management and ping-ponging automatically.

For example, we would just specify that lighting reads from "G-Buffer" and writes to "light-accumulator". A glow effect would write geometry to the "glow-map", then the blur would read from "glow-map" and write to "light-accumulator". Let the engine work out the buffer-swapping details!

Disclaimer: this is a reach-goal that I'm interested in "because it's cool." I still need to think more about it, and it shouldn't even be attempted until the main pipeline code is done!

**Comment by wrongu** [comment]
moved #128 for a more thorough description.
