### ISSUE TITLE
Link errors on VS2012

### ISSUE THREAD

**Issue by lamogui** [adam4813/Sigma#125]
Hello guys i try to compile sigma and i get somes errors : 
- GLM doesn't find function translate(truc,x,y,z) only translate(truc,vec3) (and many similars) [Corrected](not sure but i think it's because in gtc theses calls ares not supported and may be they are supported in gtx)
- libvorbisfile_static was not found [Corrected]
- A lot of libs are not take in charge by CMAKE under windows
- AWESOMIUM LINK ERROR cannot find all DLL calls symbols !

All modifications i made to get sigma compiling are visibles here : https://github.com/lamogui/Sigma branch devlop 
Commit here https://github.com/lamogui/Sigma/commit/0a274b005671e0bdc54f4988eca19ec9e8b40404

**Comment by adam4813** [comment]
Not sure the issue on this sorry.

We are targeting the dynamic libraries FYI.

This is a shortcoming on my behalf and it will change after this release. There is a prebuilt package you can extract in the root folder for the moment. It is missing GLFW and the OpenAL items as I am not going to update something that will be phased out. https://www.dropbox.com/s/d7owydeajzjmd59/win32devpackage.zip

Did you install the awesomium sdk?

**Comment by lamogui** [comment]
Yes i install the awesomium sdk, VS2012 found the file awesomium.lib (i check that) but i doesn't find the symbol... to compile well in static i need to change the /MD to /MT flag in VS2012 may be the bug come from that... but if it come i need to recompile all the libs ... (sorry for my english)

**Comment by adam4813** [comment]
I am going to close this now as awesomium is to be replaced soon. Also for linker errors you must use the same runtime type '(e.g debug, debug dll, release, release dll) for everything. We need to target the DLL variant.

Also make sure all dependencies are built as shared libraries. See issue #79
