### ISSUE TITLE
Add link to assets list in README.

### ISSUE THREAD

**Issue by adam4813** [adam4813/Sigma#127]

**Comment by aponigricon** [comment]
Why can't we just keep the assets in the repository? It would be far easier to manage.

**Comment by adam4813** [comment]
They are over 20mb raw right now. I am just talking about a link to the
wiki.

I put this here to remind myself to do it later instead of forgetting like
others things have been.

**Comment by aponigricon** [comment]
> 20mb

And why exactly is that a problem?

**Comment by wrongu** [comment]
Also remember that Trillek will _use_ Sigma, but Sigma is not Trillek. Everything included in the Sigma repository should be generic game-engine stuff. So when we want to test Trillek, we download the Trillek assets. When we want to test <insert game name here>, we download that game's assets, and Sigma shouldn't know the difference.

So it makes sense to keep them separate, even if it was 1Kb of assets.

**Comment by adam4813** [comment]
The README has been updated, so I am going to close. If you want to open an issue discussing hosted the assets via github please do.
