### ISSUE TITLE
Change coding style document to tell that we use tabs and not spaces

### ISSUE THREAD

**Issue by catageek** [adam4813/Sigma#129]
The current coding style document states that spaces should be used instead of tabs.

The issue is that the writer of the coding style document does not himself respect this ;-)

Since preference of the majority is to use tabs, the coding style document should be modified to take into account that we use tabs.

**Comment by adam4813** [comment]
https://github.com/adam4813/Sigma/wiki/Coding-Standards resolves this issue.
