### ISSUE TITLE
Square Spotlight for Video Screen

### ISSUE THREAD

**Issue by tanderegg** [adam4813/Sigma#137]
We'd like to add the ability to use a texture to define the shape of a spotlight, which will be used to create a glowing effect for video screens.  Light color will be determined by average color of the screen per frame, and light itself will be 1 to 3 meters in range and approx 45 degrees, with a square texture.  Possibly allow the color to be determined by texture as well to allow for variation based on screen contents.

**Comment by Zardoz89** [comment]
An future improvement over this, could be projecting a blurred & reduced version of the screen texture. This will be a lot more realistic.
