### ISSUE TITLE
target build directory is bin/ and not build/bin/

### ISSUE THREAD

**Issue by catageek** [adam4813/Sigma#141]
When I build Sigma on Linux, the Sigma binary and libSigma library are copied in bin/ directory instead of build/bin as previously.

The README is still considering that the target directory is buid/bin/ or build/debug/, and all the CEF installation instructions are based on this. This may confuse some users since some additional file operations are needed.

I don't confirm that it is generalized to all platforms, but at list linux users are concerned.

**Comment by adam4813** [comment]
I believe the latest merge from Meisaka fixed this.

On win32 its still build/bin/[debug/release].

**Comment by Meisaka** [comment]
The README does cover this (under the OS X section? maybe sections of instructions could be arranged better/split up)

```
mkdir build/
cd build/
cmake ..
make
```

**Comment by adam4813** [comment]
Is this still an issue or has it been resolved?

**Comment by catageek** [comment]
It is resolved following Meisaka instructions.
