### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by Zardoz89** [adam4813/Sigma#142]
Any idea what lib we will use for threads ?
GLFW3 dropped thread functions, so we need to use other lib to have threads.
C++ 11 <thread> lib is a option, but isn't supported in VS2010, enforce to use VS2012 instead.
boost::thread and TinyThread++ could other possible options.

**Comment by Zardoz89** [comment]
I think that the options are (open source, of course) : 
- C++ 11 std::thread -> but get's out compatibility with VS2010
- TinyThread++ -> Implements a subset of **std::thread** but very portable and have **fast_mutex** and minimal overhead. Should allow to be replaced in a future by std::thread with minimal changes (http://tinythreadpp.bitsnbites.eu/)
- Threading Building Blocks (TBB) -> Very different but portable and being developed by Intel (https://www.threadingbuildingblocks.org/)
- boost:thread -> Have a lot of dependency with all boost library, so this enforce us to include, at least, half boost lib.
- Posix threads -> There is a open source implementation of pthreads for windows, so could do the trick. (http://sourceware.org/pthreads-win32/)

**Comment by Meisaka** [comment]
I like the idea of adding threading, TinyThread++ and Posix threads both seem like good options.
I really don't like the idea of excluding VS2010 (since I use it), I would rather write my own cross-platform threading layer before using C++11 threads.

**Comment by Zardoz89** [comment]
Other lib : 
**cpptask** : http://code.google.com/p/cpptask/  Have threads in a portable way, and supports VS2008/10/12 and gcc (mac??), open source and supports task concurrent programming, events, mutex, semaphores, atomic types (boolean and long integer), parallel-for/reduce , Delivering exceptions from threads and tasks to caller ... Sounds good, but Need to test if it works in Mac.

**Comment by adam4813** [comment]
Ok since we are using Visual Studio 2012+ we can now use the std::threads, so I am closing this.
