### ISSUE TITLE
CMake for unit tests is broken, unable to build SigmaTest

### ISSUE THREAD

**Issue by catageek** [adam4813/Sigma#148]
The path to find the include files are not correct. I could not fix it...

**Comment by adam4813** [comment]
It is looking for GTest include files. I wonder which is the best way to store them locally (excluded those that have them in a defined usr folder or something:
- In the tests/include/libraries folder (wouldn't make the assumption that tests in inside root)
- In the root/include/libraries folder (would centralize all library includes)

**Comment by catageek** [comment]
I don't fully understand the implications of a choice or another.  Without other feedback,  feel free to choose the best solution that fits your needs.

**Comment by adam4813** [comment]
Alright fixed. You must change the Sigma's include directory property when configuring the cmake.
