### ISSUE TITLE
Recent Changes breaks Linux Compatibility

### ISSUE THREAD

**Issue by jlitewski** [adam4813/Sigma#18]
The recent changes break Linux Compatibility. So far, I found two issues:
- GLCubeSphere uses sprintf_s, which is Windows only. Use sprintf instead.
- GLMesh depends solely on SOIL. Two ideas:
  - Have SOIL as a dependency for *Nix systems
  - Modify GLMesh to use SDL if OS_SDL is defined

I'm working on fixing these issues, and I should have it done by tonight after work.

**Comment by adam4813** [comment]
The second issue will be fixed with the resource system. Once created GLMesh and others will have a resource object that is loaded via SOIL or whichever means works best on the target system.

**Comment by adam4813** [comment]
Eldalar fixed the sprintf issue.
