### ISSUE TITLE
Remove SDL2main hard dependency on Linux

### ISSUE THREAD

**Issue by catageek** [adam4813/Sigma#38]
I compiled SDL from the dev repo and the SDL2main.so file is no more installed. Of course make is complaining about the missing library.

I compiled sigma without the requirement and it compiled without error.

It would be great if SDL2main was not included as hard dependency on Linux.

**Comment by tanderegg** [comment]
OK, I haven't tried that yet, but I'll look into it!  The documentation recommended including it, but it may not be necessary for our usage.

**Comment by adam4813** [comment]
Done I believe with the new repo history change.
