### ISSUE TITLE
SIGSEGV while loading test.mc

### ISSUE THREAD

**Issue by catageek** [adam4813/Sigma#43]
In BulletPhysics.cpp, line 150, getComponent(...) returns NULL and causes a segmentation fault.

Output:
Creating component of type: GLMesh
Loading mesh: shipobj/ship.obj
Loading ambient texture: shipobj/maps/Map__1_Speckle.tga
Loading diffuse texture: shipobj/maps/Map__1_Speckle.tga

test.mc part:
@ship
#5

&GLMesh

> scale=0.1f
> z=-3.0f
> y=0.75f
> x=-18.0f
> meshFile=shipobj/ship.objs
> cullface=nones

**Comment by adam4813** [comment]
Oh you have an old test.sc, and if you are on the release branch is a hard coding issue, it can be safely ignored as that will is not a the develop branch at all.

**Comment by catageek** [comment]
I stick on the release branch.

I can ignore it, but it prevents me loading the game. What should I do to get rid of it ?

**Comment by adam4813** [comment]
Nothing can be done in the release branch unless you use the ms1assets test.sc. BulletPhysics is hard coded to look for a specific entity id and get a very specific component from it.
