### ISSUE TITLE
component access

### ISSUE THREAD

**Issue by wrongu** [adam4813/Sigma#51]
Systems that act on component A currently have no general-purpose way of accessing components owned by other systems.

**Comment by adam4813** [comment]
In general they shouldn't have to. If they need to access some form of shared data, it might be best to make it a shared resource.

**Comment by adam4813** [comment]
Closing this as per the newly found understanding of how things fit together.

**Comment by wrongu** [comment]
Newly found understanding means that this should be relabeled as "shared resource access". Of course, the solution could then be as passing the shared resource to each component when the component is created.
