### ISSUE TITLE
OpenAL sound system

### ISSUE THREAD

**Issue by wrongu** [adam4813/Sigma#52]
The following items are needed from our sound system:
- [x] Play sound effect
- [x] Play music (loop)
- [x] Stop all audio
- [x] Stop sound effect
- [x] Stop music
- [x] Audio file resource
- [x] Music component
- [x] Sound effect component
- [x] Per component volume control

**Comment by adam4813** [comment]
It looks like the PR hits all the bullet points. Closing.
