### ISSUE TITLE
Make all dependency targets consistent

### ISSUE THREAD

**Issue by adam4813** [adam4813/Sigma#79]
Check to make sure all findX files are looking for a consistent target either static or dynamic.

Also ensure that each findX uses similar naming for its variables and all search paths are available.

**Comment by adam4813** [comment]
Current dependency list:
- [x] GLFW3
- [x] Bullet
- [x] GLEW
- [x] SOIL
- [x] Awesomium

**Comment by catageek** [comment]
The README should tell the minimal version of each dependency since they are not yet the stable version proposed by the distribution site or the OS package managers. Compilation may fail if a wrong version is used.
