### ISSUE TITLE
Unique ID provider

### ISSUE THREAD

**Issue by catageek** [adam4813/Sigma#83]
A class that provide a unique ID upon request must be implemented.

This class must keep track of the IDs currently in use to ensure that no duplicate ID is provided.

(The BitArray class of my PR, a dynamic_bitset,  is a perfect storage for keep track of the IDs in use, providing that convenient functions are added.)

**Comment by adam4813** [comment]
Good idea. Can you split it out into a separate PR?

**Comment by catageek** [comment]
PR has been pushed.

**Comment by adam4813** [comment]
Is this issue now defunct?

**Comment by catageek** [comment]
A PR is nearly ready to be pulled (as soon as the big PR is actually pulled) to avoid conflicts. We can close it.
