### ISSUE TITLE
Tell which compiler are better supported

### ISSUE THREAD

**Issue by catageek** [adam4813/Sigma#88]
Since code may contain builtin functions, intinsic functions or inline asm to improve performance and simplify code writing, code compiled by certain compiler will be of better quality.

Moreover some features available starting at a version of the compiler may be used.

I personnally use GCC-4.8.2 and I use features that appeared only in this version.

It would be nice to tell which version of compilers are known to build Sigma correctly.

**Comment by adam4813** [comment]
Well for most c++11 features you need gcc 4.8 I think.

**Comment by wrongu** [comment]
I think at some point along the way, c++0x stopped working for Sigma. We should remove that from cmake and require that people use gcc 4.8+ (or whatever other c++11 compiler)

**Comment by adam4813** [comment]
It is left in for gcc 4.7 which supports most features just not be the
official name of c++11.

**Comment by wrongu** [comment]
I just remember at some point along the way, 4.7 with c++0x stopped working and I had to upgrade to 4.8. I don't remember exactly what the problem was (it may have since been removed).. I'll test it on 0x when I get a chance to confirm.

**Comment by catageek** [comment]
I use the new multiple function versions feature,  each version targeting a specific processor and/or ISA: 
**attribute** ((target ("sse2"))) for example.

This feature appear only in gcc 4.8

**Comment by adam4813** [comment]
@DeVaukz Well, clang 3.3 and up support c++11.  But Sigma requires the OS X 10.7 SDK at minimum to build and it won't run on anything less than 10.7.

Win32 Visual Studio 2010 and up works.

Unless I am informed differently I am going to lay down GCC 4.8 minimum. This should apply to Linux and Win32.
