### ISSUE TITLE
Last commit (merge from pull request #92) broken Sigma in Linux

### ISSUE THREAD

**Issue by Zardoz89** [adam4813/Sigma#94]
I get a black screen since I pulled the latest update. I need to fall back to pre-merge

**Comment by DeVaukz** [comment]
https://github.com/adam4813/Sigma/commit/c5a79f23edc63b9eee12b732acec98c32bde05b4 is crashing the OS X build of Sigma.

**Comment by adam4813** [comment]
Reverted.
