### ISSUE TITLE
Example Scenes assets not included

### ISSUE THREAD

**Issue by PhilipVinc** [adam4813/Sigma#98]
Trying to run the compiled Sigma binary will fail because assets for the example scenes are not included

**Comment by lundstig** [comment]
I think that's intended, to not clog up the repository with assets. There is a zip somewhere with everything needed, but I'm on my phone and don't have the link.

**Comment by PhilipVinc** [comment]
I can't find a link anywhere. maybe it should be added in the readme: (Where is it, by the way?)

**Comment by Zardoz89** [comment]
https://www.dropbox.com/s/7y8rzmi4i6ie0kn/assets12-13.zip

**Comment by adam4813** [comment]
The links are on the Wiki as well. http://wiki.trillek.org/
